// GENERATED by make_b163_vectors.sh with OpenSSL 3.6.4. Do not edit by hand.
//
// Independent-oracle vectors for NIST B-163 (sect163r2) ECDH. Every value is a BIG-ENDIAN hex octet
// string exactly as OpenSSL prints it (scalars and coordinates 21 bytes); the tests convert them to
// ZEPP_PROTOCOL.md §4.2's little-endian 24-byte layout before comparing. OpenSSL's ECDH output is the
// shared point's X only, so the tests check Y by symmetry and by the curve equation.
// All keys are synthetic (random, or the made-up scalars of the spec's worked example C).

struct B163OpenSSLVector {
    let name: String
    let privateA: String
    let publicAX: String
    let publicAY: String
    let privateB: String
    let publicBX: String
    let publicBY: String
    let sharedX: String
}

let b163OpenSSLVectors: [B163OpenSSLVector] = [
    .init(name: "spec-worked-example-C",
          privateA: "0114131211100f0e0d0c0b0a090807060504030201", publicAX: "075c2e9bc663a00e142c965241a24ea4c202ade4a1", publicAY: "01c85d85f59cfb85ab19f5c53b8ab7676da07350cd",
          privateB: "0194939291908f8e8d8c8b8a898887868584838281", publicBX: "000cc372216fab175c2a23ad67f009a949771531a3", publicBY: "056a25fd7307da895fc2295ff3c566fcdf1a5bf5f4",
          sharedX: "011bab57fbdc49c767354c548cf2c31a562933d231"),
    .init(name: "openssl-random-1",
          privateA: "016f9c454ae974e34bdee03d3a038ed16711c1a5ea", publicAX: "079093228a488b3ede414cc1210dd7a0b23bf3de49", publicAY: "02274ca6e040f1f0d558d2e4520b5e15248ffa9209",
          privateB: "0024e8534d92fe466d1dbb3b5b05230175387a3fe5", publicBX: "00755bfcda722026fda17f473b14a91690ca2410e0", publicBY: "065f5748b7f148553df5d856a0c7d76698e9c168c8",
          sharedX: "068eeb13f648c41cbd0d83dbe57fa2bbec65407c35"),
    .init(name: "openssl-random-2",
          privateA: "02cc656df4dfcf782f9bad40f3db4afd7c80d0210e", publicAX: "0524e3df26b93c793efc8e7b03f679e25d3c5bebba", publicAY: "0683cea80c8727ed83e6e7547b3d38eafd092c5de1",
          privateB: "01bd5fba0ec6723fdb64596bece1b828619f43ff2e", publicBX: "02d1a4b6ccb1ce4f284af8045d9c56f8c2c9787ba9", publicBY: "020ed85e936982444001b1f52e6142e577feab26ba",
          sharedX: "00f9adc14fdd96a16938f70481b3451242bbaba784"),
    .init(name: "openssl-random-3",
          privateA: "0137ece980054f98e8adaf62cd427e117299bd1f65", publicAX: "039e9884ed124a7f4aa05184d4dac16da92e802533", publicAY: "07617f6463f71b8785b36bfd918980f7640e997f60",
          privateB: "02f34235554f9605e06da690c5e4d7172739f18479", publicBX: "0740fe885f954c024e0ee125d32fada50b3f00aaf5", publicBY: "065cd27e70b4b74927e841e66fd4de0b1205f8b28b",
          sharedX: "01753d38519451f88f4d3c3f3c29da987b8bfd1688"),
    .init(name: "openssl-random-4",
          privateA: "019334140eea6666dc3dedb4961adeed14a765c47a", publicAX: "0223e7b888e86532e238f300c853dab5ce5758fd68", publicAY: "04f8e773e142b2eeed840606807d9f65d0d16e0ecb",
          privateB: "00eba1c330f00724f2539db0b46ae8b69c43dfaba5", publicBX: "036d7c9db387e4814c9cb4f7328841457f47cf2950", publicBY: "07523ec8ba72589e952a705091cb2d4ca6ddb939e7",
          sharedX: "0059103a02c5ce93abef4e61f6694ad6da33e8543b"),
    .init(name: "openssl-random-5",
          privateA: "010846227cd9626e2757edfa58d9b3d9f6060b5d61", publicAX: "064b5f09a3c41bcd70afd9ae2b5a0a6e4c4896411b", publicAY: "045bdd2f3582c6716d432f94621fa5ddbf0c7e494b",
          privateB: "02a39c2f5d0102eaad15b918a335342ba3bb9a6d2e", publicBX: "018ef9169b69b8ce1fd8d2cc6520d014a5c31a5e77", publicBY: "04b57d77e2c0cd13977d38783dc295e1764388992e",
          sharedX: "002ef345a2de4d3c4b1812ae213ce82c379235ff9e"),
    .init(name: "openssl-random-6",
          privateA: "01a2bd810483af5ee51ed3f046cf55b0d494e62018", publicAX: "06967d73e86d1715a7f1c0b858d378fd31f40280d3", publicAY: "06ec55a8e9edd59469d2935bcb9fd1970ac72318a9",
          privateB: "0016c4770c8cf12bafbdb3ac0594f18e3f6967bc6f", publicBX: "046758446b64ed8d3cf5846ced15cb290525937884", publicBY: "03434720f97a6fb8d390805d44efbe240aaa821d0a",
          sharedX: "04df7212c80529ada4747a695bb936dcc78e339821"),
    .init(name: "openssl-random-7",
          privateA: "00d82aef28eb672d33f0a6322fc2d3597fd84166b0", publicAX: "07175dac0113a1349fa1a1d7d4fd0581c80588128b", publicAY: "05e0a8c81d7a71e663d4b8107415767c34e218c9d1",
          privateB: "03669cfe0b53e05f9a3d4c421e8ea3ca181da18f7e", publicBX: "04307999139d5d8d2539b923e27ada18ac2b6b5c70", publicBY: "0423ed6868e69bd826281862fc6c3df24b4ec0aa5b",
          sharedX: "0510cbef4e8d25a889ddecada170f45bffe01ac04f"),
    .init(name: "openssl-random-8",
          privateA: "00c792be73ba7884c63fc8385f97dbe556e6c78e19", publicAX: "033d7d16b1f5a3d71a7396733e1d3d4df1802b2516", publicAY: "0758d5a702118913be37818779d27faa9d3afc993d",
          privateB: "015fd2ce058e965ed59e6157ef54d111f10c0f31df", publicBX: "033dda47699dfcc05bdb7eb6d0923e090a3405ab26", publicBY: "0647844107c8e71c3430a85d4bddc8d5585a172448",
          sharedX: "033408fb3416cb8d304a71ae99a09d708dd4884ca2"),
]
