#!/bin/bash
# Regenerates B163OpenSSLVectors.swift: sect163r2 (NIST B-163) ECDH vectors computed by OpenSSL 3,
# an implementation independent of ZeppKit's tiny-ECDH-c port. ZeppKitTests assert the Swift ECDH
# agrees with every vector after converting OpenSSL's big-endian octet strings into the wire layout
# ZEPP_PROTOCOL.md §4.2 prescribes (24-byte little-endian field elements / scalars).
#
# All keys are synthetic: fresh random keypairs, plus the made-up scalars of the spec's worked
# example C (§4.6) imported into OpenSSL so the spec's own vector is cross-checked too.
#
# Usage (from this directory): ./make_b163_vectors.sh > B163OpenSSLVectors.swift
set -euo pipefail
OSSL=${OPENSSL:-/opt/homebrew/opt/openssl@3/bin/openssl}
COUNT=${COUNT:-8}
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Private scalar and public point of a PEM/DER key, as big-endian hex (priv 21 bytes, pub X/Y 21 bytes each).
key_fields() {
  "$OSSL" pkey -in "$1" -text -noout | python3 -c '
import sys, re
text = sys.stdin.read()
def block(name):
    m = re.search(name + r":\s*\n((?:\s+[0-9a-f:]+\n)+)", text)
    return "".join(m.group(1).split()).replace(":", "")
priv = int(block("priv"), 16)
pub = block("pub")
assert pub[:2] == "04" and len(pub) == 2 + 84, "expected an uncompressed 21+21-byte point"
print("%042x %s %s" % (priv, pub[2:44], pub[44:]))
'
}

# Import a raw scalar (big-endian hex, 21 bytes) as an OpenSSL EC private key. OpenSSL computes the
# public point itself on load, so the spec vector's public key is checked, not assumed.
import_scalar() {
  cat > "$WORK/asn1.cnf" <<EOF
asn1=SEQUENCE:ec_key
[ec_key]
version=INTEGER:1
privateKey=FORMAT:HEX,OCTETSTRING:$1
params=EXPLICIT:0,OID:sect163r2
EOF
  "$OSSL" asn1parse -genconf "$WORK/asn1.cnf" -out "$WORK/raw.der" -noout
  "$OSSL" pkey -inform DER -in "$WORK/raw.der" -out "$2"
}

derive_x() { # own private key, peer key -> shared X, big-endian hex
  "$OSSL" pkey -in "$2" -pubout -out "$WORK/peer_pub.pem"
  "$OSSL" pkeyutl -derive -inkey "$1" -peerkey "$WORK/peer_pub.pem" -out "$WORK/shared.bin"
  xxd -p "$WORK/shared.bin" | tr -d '\n'
}

emit() { # name, keyA, keyB
  read -r privA axA ayA <<<"$(key_fields "$2")"
  read -r privB bxB byB <<<"$(key_fields "$3")"
  sAB=$(derive_x "$2" "$3")
  sBA=$(derive_x "$3" "$2")
  [ "$sAB" = "$sBA" ] || { echo "OpenSSL derive is asymmetric for $1" >&2; exit 1; }
  printf '    .init(name: "%s",\n' "$1"
  printf '          privateA: "%s", publicAX: "%s", publicAY: "%s",\n' "$privA" "$axA" "$ayA"
  printf '          privateB: "%s", publicBX: "%s", publicBY: "%s",\n' "$privB" "$bxB" "$byB"
  printf '          sharedX: "%s"),\n' "$sAB"
}

cat <<EOF
// GENERATED by make_b163_vectors.sh with $("$OSSL" version | cut -d' ' -f1-2). Do not edit by hand.
//
// Independent-oracle vectors for NIST B-163 (sect163r2) ECDH. Every value is a BIG-ENDIAN hex octet
// string exactly as OpenSSL prints it (scalars and coordinates 21 bytes); the tests convert them to
// ZEPP_PROTOCOL.md §4.2's little-endian 24-byte layout before comparing. OpenSSL's ECDH output is the
// shared point's X only, so the tests check Y by symmetry and by the curve equation.
// All keys are synthetic (random, or the made-up scalars of the spec's worked example C).

struct B163OpenSSLVector {
    let name: String
    let privateA: String
    let publicAX: String
    let publicAY: String
    let privateB: String
    let publicBX: String
    let publicBY: String
    let sharedX: String
}

let b163OpenSSLVectors: [B163OpenSSLVector] = [
EOF

# The spec's worked example C: phone effective scalar 01..14 01 00 00 00 (LE), strap 81..94 01 00 00 00 (LE).
import_scalar "$(python3 -c 'print(bytes(list(range(1, 21)) + [1, 0, 0, 0])[::-1][3:].hex())')" "$WORK/specA.pem"
import_scalar "$(python3 -c 'print(bytes(list(range(0x81, 0x95)) + [1, 0, 0, 0])[::-1][3:].hex())')" "$WORK/specB.pem"
emit "spec-worked-example-C" "$WORK/specA.pem" "$WORK/specB.pem"

for i in $(seq 1 "$COUNT"); do
  "$OSSL" genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sect163r2 -pkeyopt ec_param_enc:named_curve -out "$WORK/a.pem"
  "$OSSL" genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sect163r2 -pkeyopt ec_param_enc:named_curve -out "$WORK/b.pem"
  emit "openssl-random-$i" "$WORK/a.pem" "$WORK/b.pem"
done

echo "]"
